global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'Servers'
    static_configs:
      - targets:
          - 'terminal2:9182'
          - '10.11.10.66:9182'
          - 'srv1czup:9182'
          - 'hv10:9182'
          - 'db:9182'
          - 'db2:9182'
          - 'srv1c:9182'
        labels:
          environment: 'production'
  - job_name: 'snmp'
    static_configs:
      - targets:
          - 10.11.10.1
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.18.0.1:9116 
  - job_name: 'windows_terminal_sessions'
    static_configs:
      - targets: ['terminal2:8080']