global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'Servers'
    static_configs:
      - targets:
          - 'terminal-rtsz:9182'
          - 'terminal2:9182'
          - 'terminal-rtsz'
          - '10.7.10.66:9182'
          - 'srv1czup:9182'
          - 'hv10:9182'
          - 'db:9182'
          - 'db2:9182'
          - 'terminal_ipku:9182'
          - 'srv1c:9182'
          - 'srv1cerp:9182'
          - 'mail:9182'
        labels:
          environment: 'production'

  - job_name: 'snmp'
    static_configs:
      - targets:
          - 10.11.10.1
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.18.0.1:9116

  # Мониторинг регистраторов по SNMP
  - job_name: 'dvr_recorders'
    scrape_interval: 1m
    scrape_timeout: 30s
    static_configs:
      - targets:
          - 10.8.10.50  # sklad 1
          - 10.8.10.100  # sklad 2
          - 10.8.10.10  # sklad 3
    metrics_path: /snmp
    params:
      module: [dvr_nvr]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp_exporter:9116


  - job_name: 'cameras_icmp'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - 10.8.10.50
          - 10.8.10.51
          - 10.8.10.52
          - 10.8.10.53
          - 10.8.10.55
          - 10.8.10.56
          - 10.8.10.57
          - 10.8.10.58
          - 10.8.10.59
          - 10.8.10.60
          - 10.8.10.61
          - 10.8.10.62
          - 10.8.10.63
          - 10.8.10.64
          - 10.8.10.65
          - 10.8.10.66
          - 10.8.10.67
          - 10.8.10.68
          - 10.8.10.69
          - 10.8.10.70
          - 10.8.10.71
          - 10.8.10.72
          - 10.8.10.73
          - 10.8.10.74
          - 10.8.10.75
          - 10.8.10.76
          - 10.8.10.77
          - 10.8.10.78
          - 10.8.10.79
          - 10.8.10.80
          - 10.8.10.81
          - 10.8.10.82
        labels:
          device_type: 'camera'
          location: 'Склад 1'
      - targets:
          - 10.8.10.100
          - 10.8.10.101
          - 10.8.10.102
          - 10.8.10.103
          - 10.8.10.104
          - 10.8.10.105
          - 10.8.10.106
          - 10.8.10.131
          - 10.8.10.108
          - 10.8.10.109
          - 10.8.10.110
          - 10.8.10.111
          - 10.8.10.112
          - 10.8.10.54
          - 10.8.10.114
          - 10.8.10.115
          - 10.8.10.2
          - 10.8.10.117
          - 10.8.10.118
          - 10.8.10.119
          - 10.8.10.120
          - 10.8.10.121
          - 10.8.10.132
          - 10.8.10.123
          - 10.8.10.124
          - 10.8.10.125
          - 10.8.10.126
          - 10.8.10.127
          - 10.8.10.128
          - 10.8.10.129
          - 10.8.10.133
          - 10.8.10.130
          - 10.8.10.205
        labels:
          device_type: 'camera'
          location: 'Склад 2'
      - targets:
          - 10.8.10.10
          - 10.8.10.24
          - 10.8.10.23
          - 10.8.10.28
          - 10.8.10.20
          - 10.8.10.26
          - 10.8.10.22
          - 10.8.10.21
          - 10.8.10.27
          - 10.8.10.25
          - 10.8.10.215
          - 10.8.10.218
          - 10.8.10.126
          - 10.8.10.223
          - 10.8.10.205
          - 10.8.10.225
          - 10.8.10.219
          - 10.8.10.221
          - 10.8.10.213
          - 10.8.10.132
          - 10.8.10.220
          - 10.8.10.229
          - 10.8.10.224
          - 10.8.10.216
          - 10.8.10.11
          - 10.8.10.29
          - 10.8.10.30
          - 10.8.10.31
          - 10.8.10.32
          - 10.8.10.33
          - 10.8.10.34
          - 10.8.10.204
        labels:
          device_type: 'camera'
          location: 'Склад 3'
      - targets:
          - 10.8.10.200
          - 10.8.10.201
          - 10.8.10.202
          - 10.8.10.204
          - 10.8.10.206
          - 10.8.10.207
          - 10.8.10.29
          - 10.8.10.34
          - 10.8.10.30
          - 10.8.10.32
          - 10.8.10.232
          - 10.8.10.208
          - 10.8.10.203
          - 10.8.10.211
          - 10.8.10.213
          - 10.8.10.214
          - 10.8.10.216
          - 10.8.10.217
          - 10.8.10.219
          - 10.8.10.220
          - 10.8.10.221
          - 10.8.10.222
          - 10.8.10.224
          - 10.8.10.226
          - 10.8.10.227
          - 10.8.10.228
          - 10.8.10.229
          - 10.8.10.230
          - 10.8.10.215
          - 10.8.10.205
          - 10.8.10.209
          - 10.8.10.210
          - 10.8.10.212
        labels:
          device_type: 'camera'
          location: 'Склад 4'
      - targets:
          - 10.9.10.10
          - 10.9.10.11
          - 10.9.10.12
          - 10.9.10.13
          - 10.9.10.14
          - 10.9.10.15
          - 10.9.10.16
          - 10.9.10.17
          - 10.9.10.19
          - 10.9.10.20
          - 10.9.10.21
          - 10.9.10.27
          - 10.9.10.28
          - 10.9.10.22
          - 10.9.10.29
          - 10.9.10.23
          - 10.9.10.180
          - 10.9.10.24
          - 10.9.10.25
          - 10.9.10.26
          - 10.9.10.142
          - 10.9.10.147
          - 10.9.10.246
          - 10.9.10.247
          - 10.9.10.248
        labels:
          device_type: 'camera'
          location: 'Прод 1'
      - targets:
          - 10.9.10.40
          - 10.9.10.41
          - 10.9.10.42
          - 10.9.10.43
          - 10.9.10.44
          - 10.9.10.45
          - 10.9.10.46
          - 10.9.10.47
          - 10.9.10.48
          - 10.9.10.49
          - 10.9.10.50
          - 10.9.10.51
          - 10.9.10.52
          - 10.9.10.65
          - 10.9.10.53
          - 10.9.10.54
          - 10.9.10.55
          - 10.9.10.56
          - 10.9.10.57
          - 10.9.10.58
          - 10.9.10.59
          - 10.9.10.60
          - 10.9.10.75
          - 10.9.10.61
          - 10.9.10.62
          - 10.9.10.63
          - 10.9.10.76
          - 10.9.10.64
          - 10.9.10.37
          - 10.9.10.102
          - 10.9.10.66
          - 10.9.10.211
          - 10.9.10.77
        labels:
          device_type: 'camera'
          location: 'Прод 2'
      - targets:
          - 10.9.10.80
          - 10.9.10.81
          - 10.9.10.82
          - 10.9.10.83
          - 10.9.10.84
          - 10.9.10.85
          - 10.9.10.86
          - 10.9.10.87
          - 10.9.10.88
          - 10.9.10.89
          - 10.9.10.90
          - 10.9.10.91
          - 10.9.10.92
          - 10.9.10.93
          - 10.9.10.94
          - 10.9.10.95
          - 10.9.10.202
          - 10.9.10.11
          - 10.9.10.12
          - 10.9.10.13
          - 10.9.10.14
          - 10.9.10.15
          - 10.9.10.16
          - 10.9.10.17
          - 10.9.10.19
          - 10.9.10.20
          - 10.9.10.21
          - 10.9.10.22
          - 10.9.10.23
          - 10.9.10.24
          - 10.9.10.25
          - 10.9.10.26
        labels:
          device_type: 'camera'
          location: 'Прод 3'
      - targets:
          - 10.6.10.10
          - 10.6.10.11
          - 10.6.10.221
          - 10.6.10.13
          - 10.6.10.14
          - 10.6.10.15
          - 10.6.10.26
          - 10.6.10.17
          - 10.6.10.18
          - 10.6.10.19
          - 10.6.10.20
          - 10.6.10.21
          - 10.6.10.22
          - 10.6.10.23
          - 10.6.10.24
          - 10.6.10.25
          - 10.6.10.2
          - 10.6.10.3
          - 10.6.10.4
          - 10.6.10.5
          - 10.6.10.6
        labels:
          device_type: 'camera'
          location: 'Прод 4 ТПА'
      - targets:
          - 10.9.10.161
          - 10.9.10.181
          - 10.9.10.162
          - 10.9.10.180
          - 10.9.10.220
          - 10.9.10.163
          - 10.9.10.164
          - 10.9.10.221
          - 10.9.10.165
          - 10.9.10.166
          - 10.9.10.167
          - 10.9.10.223
          - 10.9.10.168
          - 10.9.10.169
          - 10.9.10.222
          - 10.9.10.224
          - 10.9.10.182
          - 10.9.10.170
          - 10.9.10.172
          - 10.9.10.173
          - 10.9.10.174
          - 10.9.10.175
          - 10.9.10.176
          - 10.9.10.177
          - 10.9.10.178
          - 10.9.10.171
          - 10.9.10.179
        labels:
          device_type: 'camera'
          location: 'Офис'
      - targets:
          - 10.13.10.73
          - 10.13.10.67
          - 10.13.10.68
          - 10.13.10.69
          - 10.13.10.70
          - 10.13.10.71
          - 10.13.10.72
          - 10.13.10.74
          - 10.13.10.75
        labels:
          device_type: 'camera'
          location: 'Склад МСК'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: 'windows_terminal2_sessions'
    static_configs:
      - targets: ['terminal2:8080']

  - job_name: 'windows_terminal_ipku_sessions'
    static_configs:
      - targets: ['terminal_ipku:8080']

  - job_name: 'windows_terminal_rtsz_sessions'
    static_configs:
      - targets: ['terminal-rtsz:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: 
          - '10.10.10.137:9100'
        labels:
          service: 'node-exporter'
          group: 'servers'
          instance: 'main-server'
          os: 'linux'

  - job_name: 'bitrix24-online-users'
    scrape_interval: 60s
    scrape_timeout: 30s
    metrics_path: '/'
    static_configs:
      - targets: ['10.10.10.137:8090']
        labels:
          service: 'bitrix24'
          instance: 'rostherm-crm'
          source: 'bash-exporter'