{
 "title": "Камеры",
 "description": "Prometheus Blackbox Exporter Overview Minimal View showing status, SSL expiry and duration graph",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(probe_success,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Склад 1 10.8.10.50",
   "type": "stat",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"cameras_icmp\", location=\"Склад 1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Склад 2 10.8.10.100",
   "type": "stat",
   "gridPos": { "h": 15, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"cameras_icmp\", location=\"Склад 2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Склад 3 10.8.10.10",
   "type": "stat",
   "gridPos": { "h": 15, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"cameras_icmp\", location=\"Склад 3\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Прод 1 10.9.10.10",
   "type": "stat",
   "gridPos": { "h": 15, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"cameras_icmp\", location=\"Прод 1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}