{
 "title": "Монитор",
 "description": "Windows monitoring Dashboard.\r\n\r\n(Translated StarsL.cn's work. ID: 10467)",
 "tags": [
  "Prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(windows_cs_hostname, job)"
    }
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\"}, hostname)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",hostname=~\"$hostname\"}, instance)"
    }
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",instance=~\"$instance\"}, hostname)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Resource overview. Currently selected host:【$show_hostname】 Instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$job:Обзор ресурсов сервера",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"$job\"} * on(instance) group_right(product) windows_cs_hostname",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": " Использование дисков",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{job=~\"$job\",volume=~\"^[CDEFG]:$\"} / windows_logical_disk_size_bytes{job=~\"$job\",volume=~\"^[CDEFG]:$\"})*100",
     "legendFormat": "{{volume}} {{instance}}"
    }
   ]
  },
  {
   "title": "(Terminal2)Статус \"Активно\"",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_terminal_sessions_active_sessions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(Terminal_ipku)Статус \"Активно\"",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_terminal_ipku_sessions_active_sessions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Максимальное количество данных чтения/записи диска для каждого хоста",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_logical_disk_read_bytes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Read",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_logical_disk_write_bytes_total[2m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Writing",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Сетевые данные о максимальном трафике сетевой карты каждого хоста",
   "type": "stat",
   "gridPos": { "h": 13, "w": 5, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "max by (instance) (irate(windows_net_bytes_sent_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8 ",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "-max by (instance) (irate(windows_net_bytes_received_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}}_Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Тоннели",
   "type": "table",
   "description": "Status link/states: The current operational state of the interface",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifOperStatus{instance='10.11.10.1'}"
    },
    {
     "expr": "ifType_info{instance='10.11.10.1'}"
    }
   ]
  },
  {
   "title": "(Terminal2)Статус \"Диск\"",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_terminal_sessions_inactive_sessions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(Terminal_ipku)Статус \"Диск\"",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_terminal_ipku_sessions_inactive_sessions",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Details of resources 【$show_hostname：$instance】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of CPU cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 73 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "windows_cs_logical_processors{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"})*100"
      }
     ]
    },
    {
     "title": "Memory Details",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 4, "y": 73 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Total Physical Memory",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_os_physical_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Remaining Physical Memory",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_os_virtual_memory_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Virtual memory",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "expr": "windows_os_virtual_memory_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "Free virtual memory"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 9, "y": 73 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_reads_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_writes_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Disk Read/Write",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 73 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_write_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m])\r",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 73 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[5m]))*100",
       "legendFormat": "CPU Utilization"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 77 },
     "repeat": "host",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "windows_cs_physical_memory_bytes{job=~\"$job\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[2m])))*100"
      }
     ]
    },
    {
     "title": "system_threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_system_threads{job=~\"$job\",instance=~\"$instance\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "system_threads",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Network discarded/error packets",
     "type": "graph",
     "gridPos": { "h": 9, "w": 5, "x": 4, "y": 81 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_packets_outbound_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_outbound_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "outbound",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_packets_received_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_received_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "received",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Network Details",
     "type": "graph",
     "gridPos": { "h": 9, "w": 5, "x": 9, "y": 81 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_bytes_sent_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8>0\r",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{nic}}-Sent-Upload",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_net_bytes_received_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8\n",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{nic}}-Received-Download",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Network Utilization",
     "type": "graph",
     "gridPos": { "h": 9, "w": 5, "x": 14, "y": 81 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(irate(windows_net_bytes_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m]) * 8 / windows_net_current_bandwidth_bytes{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}) * 100",
       "legendFormat": "{{nic}}"
      }
     ]
    },
    {
     "title": "System exception dispatches",
     "type": "graph",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_system_exception_dispatches_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "exceptions",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  }
 ]
}